"""Fix review repr

Revision ID: 2ac908af2a0e
Revises: 3d54f2336a1a
Create Date: 2023-08-28 14:35:07.057517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac908af2a0e'
down_revision = '3d54f2336a1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
